server:
  port: 8989

  error:
    whitelabel:
      enabled: false

    path: /error

spring:
  thymeleaf:
    prefix: file:///C:///personal-project//SpringReactAllinOne//target//classes//static/

  output:
    ansi:
      enabled: always

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/allinone?serverTimezone=Asia/Seoul
    username: root
    password: mariadb

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationTime: 604800000

